// Builds proxy/worker.dashboard.js: proxy/worker.js with the station list
// pasted in, as one self-contained file for the Cloudflare dashboard editor
// (which can't import ../stations.json).
//
//   npm run build:relay
import { readFileSync, writeFileSync } from 'node:fs';

export function buildDashboardWorker() {
  const root = new URL('../', import.meta.url);
  const source = readFileSync(new URL('proxy/worker.js', root), 'utf8');
  const stations = JSON.parse(readFileSync(new URL('stations.json', root), 'utf8'))
    .map(({ id, name, url }) => `  ${JSON.stringify({ id, name, url })},`)
    .join('\n');
  const importLine = "import stations from '../stations.json';";
  if (!source.includes(importLine)) throw new Error(`proxy/worker.js no longer contains: ${importLine}`);
  return (
    '// GENERATED by `npm run build:relay` from proxy/worker.js and stations.json.\n' +
    '// Paste this whole file into the Cloudflare dashboard editor. Do not edit it by hand.\n' +
    source.replace(importLine, `const stations = [\n${stations}\n];`)
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(new URL('../proxy/worker.dashboard.js', import.meta.url), buildDashboardWorker());
  console.log('Wrote proxy/worker.dashboard.js');
}
